### ISSUE TITLE
Items on navigation for mobile device should span whole width

### ISSUE THREAD

**Issue by mohammedzamakhan** [collab-ui/collab-ui#115]
## Issue Type

![momentum design_ nexus 5x](https://user-images.githubusercontent.com/2327532/54049165-6d409580-41a1-11e9-8e7e-e1896165f844.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment]
Fixed in #150
