### ISSUE TITLE
Navigation should close on mobile devices after selection (https://react.collab-ui.com/)

### ISSUE THREAD

**Issue by mohammedzamakhan** [collab-ui/collab-ui#116]
## Issue Type

Doesn't closes after selection
![react collab-ui com_develop nexus 5x](https://user-images.githubusercontent.com/2327532/54049360-dcb68500-41a1-11e9-86a2-c4595a7b2395.png)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment]
Fixed in #150
