### ISSUE TITLE
Misleading Avatar `type` Property Usage Demo

### ISSUE THREAD

**Issue by akoushke** [collab-ui/collab-ui#123]
On a demo page this is the code to use:

```js
<div className="docs-example docs-example--spacing">
          <h3>
            <p><code className="small">type=(default)</code></p>
          </h3>
          <div><Avatar title="Tom Smith"/></div>
        </div>
```

However, `default` is not an option (anymore?). I got a `Proptype warning` using `default`. Therefore, I changed it to `""`.

**Comment by pauljeter** [comment]
The documentation has been updated on the new site: https://momentum.design/components/avatar/code
