### ISSUE TITLE
Primary Button is not accessible

### ISSUE THREAD

**Issue by mohammedzamakhan** [collab-ui/collab-ui#125]
## Issue Type
Bug Report

## Component or Pattern Affected
Button

## Expected Behavior
Colors should be accessible to all users

## Current Behavior

Primary Button is not accessible according to AA or AAA standards

## Possible Solution

Black (dark) color instead of white(light) color for the primary button is accessible

## Steps to Reproduce (for bugs)
<img width="1440" alt="Screen Shot 2019-03-14 at 11 11 50 AM" src="https://user-images.githubusercontent.com/2327532/54372970-753d8100-464a-11e9-926c-49323a2cdb6e.png">

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment]
Color updates are in the works and will be applied to all components soon.

**Comment by mohammedzamakhan** [comment]
@pauljeter a very good article that I read about accessibility yesterday https://www.bounteous.com/insights/2019/03/22/orange-you-accessible-mini-case-study-color-ratio/
