### ISSUE TITLE
Schematics folder is not bundled in @collab-ui/angular@5.0.0

### ISSUE THREAD

**Issue by mohammedzamakhan** [collab-ui/collab-ui#167]
## Issue Type
Bug Report 

## Component or Pattern Affected
Schematics folder is not included in the npm package, which throws the error when you run `ng add @collab-ui/angular`

```
Error: Collection "@collab-ui/angular" cannot be resolved.
```
## Expected Behavior

The command `ng add @collab-ui/angular` should add collab ui to any Angular CLI project

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment]
I noticed this issue as well after publishing. Looking into adding a script to copy the folder to the dist package.

**Comment by mohammedzamakhan** [comment]
@pauljeter Now getting the error 
```
Cannot find module '@angular/cdk/schematics'
Error: Cannot find module '@angular/cdk/schematics'
```

**Comment by mohammedzamakhan** [comment]
@pauljeter It's not deployed again in v5.1.1
