### ISSUE TITLE
[Input] iconNode prop used by Input does not display correctly

### ISSUE THREAD

**Issue by robstax** [collab-ui/collab-ui#23]
**I'm submitting a ...** (check one with "x")

* [x] bug report
* [ ] feature request
* [ ] support request => Please do not submit support request here, instead see https://github.com/collab-ui/collab-ui-react/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Component Affected**
Input + Icon

**Current behavior**
When using the `iconNode` prop with an `<Input>` component, if the `iconNode` is wrapped in something (like a `<Tooltip>`), the `iconNode` does not display correctly (should be at end of Input).
![04!UNITO-UNDERSCORE!38!UNITO-UNDERSCORE!36](https://user-images.githubusercontent.com/11569788/48796792-64d95300-ecb5-11e8-9bca-5181e61ef020.jpg)

**Expected/desired behavior**
The content in the `iconNode` prop should be aligned at the the end of the input.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via images or video.

```
render() {
  const iconNode = (
    <Tooltip
      direction="bottom-center"
      tooltip="Rob's Tooltip"
      trigger="MouseEnter"
    >
      <Icon
        name="info_16"
        ariaLabel={'custom icon'}
      />
    </Tooltip>
  );
  return (
    <div className='row'>
      <Input
        name='inputLabel'
        label='Robs Label'
        htmlId='inputLabel'
        iconNode={iconNode}
        inputSize='small-5'
      />
    </div>
  );
}
```

**Please tell us about your environment:**
macOS 10.14

* **Toolkit Version version:**
v10
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by bfbiggs** [comment]
Resolved in #51
