### ISSUE TITLE
Need a new container with 'x' button on top right for quote message feature 

### ISSUE THREAD

**Issue by stanjiawang** [collab-ui/collab-ui#27]
Hey there! Before you post an issue here, did you try reporting this to the "Collab UI Q&A" space in Webex Teams? Please ask about your issue there before creating a new GitHub issue.

**I'm submitting a ...**  (check one with "x")

- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/collab-ui/collab-ui-react/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Component Affected**
Need a new container for quote message feature.

**Current behavior**
No container could meet the current need for quote message feature.

**Expected/desired behavior**
Need a new container with an 'x' button on top right of the box;
https://cisco.invisionapp.com/d/main/#/console/16027196/332376724/preview
![screen shot 2018-12-30 at 11 18 33 pm](https://user-images.githubusercontent.com/14055396/50556074-46d61980-0c89-11e9-9ea4-4bafe479d2f7.png)
![screen shot 2018-12-30 at 11 18 41 pm](https://user-images.githubusercontent.com/14055396/50556078-4b9acd80-0c89-11e9-8007-1e7095cf4fbe.png)

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via images or video.

**Please tell us about your environment:**
webex teams web client

* **Toolkit Version version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by andrewholsted** [comment]
@pauljeter - we have a deadline for this on Monday. I also think it may be web specific? Any concerns with us implementing this in the web client directly?

**Comment by pauljeter** [comment]
@andrewholsted, please do what you need to do to meet your deadlines. We need to spin our weekly or bi-weekly look ahead meetings again to ensure we are on the same schedule going forward.
