### ISSUE TITLE
[Icon] not visible with dark background(Black)

### ISSUE THREAD

**Issue by AMANDUA** [collab-ui/collab-ui#29]
Hey there! Before you post an issue here, did you try reporting this to the "Collab UI Q&A" space in Webex Teams? Please ask about your issue there before creating a new GitHub issue.

**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/collab-ui/collab-ui-react/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Component Affected**
Icon

**Current behavior**

![image](https://user-images.githubusercontent.com/17237753/50888016-a3b89900-141a-11e9-9552-7332b478776e.png)

**Expected/desired behavior**

![image](https://user-images.githubusercontent.com/17237753/50888145-fe51f500-141a-11e9-806e-b265f9f943e8.png)

**Reproduction of the problem**
Mount ```Icon``` without color props on a black background div.

**Comment by bfbiggs** [comment]
@AMANDUA are you concerned there isn't an example of how to change the color - or do you think the cui--dark class in the Icon's DOM ancestry should change it to white?  The only technical complication we have with this specific component is that by default the cui-icon class only sets the fill property to 'inherit'.  Adding the cui--dark prefix (fill to white) wouldn't necessarily be an issue except that we previously added an onClick prop to Icon which wraps it in a Button.  Thus, when wrapped in a Button and preceded by cui--dark, we would lose the color/fill set by the button specifically.

**Comment by AMANDUA** [comment]
@bfbiggs  - I am not concerned setting a icon color, it can be achived by color props.correct?But i don't want to send the color props as it will be the same throughout.
In my case the background color get changed, when i switch from dark mode to contrast mode.
