### ISSUE TITLE
[CallControl]: allow colorObj as props to customize background color

### ISSUE THREAD

**Issue by pradeep0601** [collab-ui/collab-ui#84]
## Issue Type
Feature Request

## Component or Pattern Affected
CallControl

## Expected Behavior
- `background-color` and `border` collab styles value should be customizable based on the `colorObj` props value. If `colorObj` is null/undefined then the styles value should be default (as it is now)

- As an instance 
1. In meeting, CallControl type= `microphone-muted` default color is `black` and it turns to `red` on active, but as per requirement when `microphone-muted` CallControl collapsed to the center, we want its `background-color` to be lighten by some `opacity` and `border` to be set with color red as below - 
![microphone-muted_navigation](https://user-images.githubusercontent.com/8437271/53148538-fe741180-35d0-11e9-817f-3c715352c451.gif)

2. Similarly, In roster panel we want some other behavior as below - 
![microphone-muted_roaster_panel](https://user-images.githubusercontent.com/8437271/53148606-409d5300-35d1-11e9-8920-f23b795bb2d0.gif)

## Current Behavior
We have achieved the above mentioned scenario by overriding default behavior.
1. In meeting case:

_Normal mode:_
```

.cui-button--red {
    background-color: rgba($flamingo, .12);
    border: 1px solid $flamingo;
}

```
_High contrast mode:_ 
```

.cui--contrast {
  & .cui-button--red {
      background-color: rgba($red-base-contrast, .12);
      border: 1px solid $red-base-contrast;
  }
}

```
2. Roster panel case:
Same as above, we have overridden collab styles in this case as well. 

## Possible Solution
CallControl should allow a props of object type by using which user can pass `background-color`, `opacity`, `border` etc. and these value can be use to decide the backgroundColor and border of CallControl.

## Steps to Reproduce (for bugs)

1. Start any meeting
2. Mute yourself from meeting controls
3. When `microphone-muted` collapsed to center, its background color will be lighten with some border.
4. If you are a host, go to roster panel and hover participant list, there you will see `microphone-muted` customized backgroundColor. Mute any user to check muted behavior as well.

## Your Environment

* Library: React
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment]
@pradeep0601, you can achieve this by passing the `style` prop in the CallControl component. i.e.
``` jsx
        <CallControl
          type='microphone-muted'
          ariaLabel='For the Win'
          iconColor='red'
          style={
            {
              fill: 'red',
              backgroundColor: 'pink',
              border: '1px solid red'
            }
          }
        />
```
